/* AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by scripts/tilesets/generate-tileset-manifest.mjs
 */

export type GeneratedTilesetManifestEntry = {
  readonly label: string;
  readonly path: string;
  readonly tileSize: number;
  readonly tileLayoutVersion: "slashem" | "3.4.3" | "3.6.7" | "5.0";
};

export const GENERATED_TILESET_MANIFEST: ReadonlyArray<GeneratedTilesetManifestEntry> =
  [
  {
    "label": "Abigaba",
    "path": "assets/slashem/Abigaba.bmp",
    "tileSize": 24,
    "tileLayoutVersion": "slashem"
  },
  {
    "label": "Absurd",
    "path": "assets/slashem/Absurd.png",
    "tileSize": 128,
    "tileLayoutVersion": "slashem"
  },
  {
    "label": "Absurdly Evil",
    "path": "assets/3.6/Absurdly Evil.png",
    "tileSize": 64,
    "tileLayoutVersion": "3.6.7"
  },
  {
    "label": "DawnHack",
    "path": "assets/3.6/DawnHack.bmp",
    "tileSize": 32,
    "tileLayoutVersion": "3.6.7"
  },
  {
    "label": "NetHack Modern",
    "path": "assets/3.6/NetHack Modern.bmp",
    "tileSize": 64,
    "tileLayoutVersion": "3.6.7"
  },
  {
    "label": "Nevanda",
    "path": "assets/3.6/Nevanda.png",
    "tileSize": 32,
    "tileLayoutVersion": "3.6.7"
  },
  {
    "label": "RZTiles",
    "path": "assets/3.6/RZTiles.bmp",
    "tileSize": 32,
    "tileLayoutVersion": "3.6.7"
  },
  {
    "label": "Vanilla NetHack Tiles",
    "path": "assets/3.6/Vanilla NetHack Tiles.png",
    "tileSize": 16,
    "tileLayoutVersion": "3.6.7"
  },
  {
    "label": "Nevanda (5.0)",
    "path": "assets/5.0/Nevanda (5.0).png",
    "tileSize": 32,
    "tileLayoutVersion": "5.0"
  },
  {
    "label": "Vanilla NetHack Tiles (5.0)",
    "path": "assets/5.0/Vanilla NetHack Tiles (5.0).png",
    "tileSize": 16,
    "tileLayoutVersion": "5.0"
  }
] as const;
