/* AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by scripts/game/generate-startup-character-rulesets.mjs
 * Sources:
 * - imported/role-sources/3.6.7/role.c
 * - imported/role-sources/3.7/role.c
 * - imported/role-sources/slashem/role.c
 * - imported/role-sources/evilhack/role.c
 */

export const GENERATED_STARTUP_ROLE_OPTIONS = [
  "Archeologist",
  "Barbarian",
  "Caveman",
  "Healer",
  "Knight",
  "Monk",
  "Priest",
  "Rogue",
  "Ranger",
  "Samurai",
  "Tourist",
  "Valkyrie",
  "Wizard",
  "Flame Mage",
  "Ice Mage",
  "Necromancer",
  "Undead Slayer",
  "Yeoman",
  "Convict",
  "Druid",
  "Infidel",
  "Dark Knight"
] as const;

export const GENERATED_STARTUP_RACE_OPTIONS = [
  "human",
  "elf",
  "dwarf",
  "gnome",
  "orc",
  "doppelganger",
  "drow",
  "hobbit",
  "lycanthrope",
  "vampire",
  "giant",
  "centaur",
  "illithid",
  "tortle",
  "draugr",
  "aasimar"
] as const;

export const GENERATED_STARTUP_CHARACTER_RULESETS = {
  "3.6.7": {
    "roles": [
      "Archeologist",
      "Barbarian",
      "Caveman",
      "Healer",
      "Knight",
      "Monk",
      "Priest",
      "Rogue",
      "Ranger",
      "Samurai",
      "Tourist",
      "Valkyrie",
      "Wizard"
    ],
    "races": [
      "human",
      "elf",
      "dwarf",
      "gnome",
      "orc"
    ],
    "roleConstraints": {
      "Archeologist": {
        "races": [
          "human",
          "dwarf",
          "gnome"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Barbarian": {
        "races": [
          "human",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Caveman": {
        "races": [
          "human",
          "dwarf",
          "gnome"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Healer": {
        "races": [
          "human",
          "gnome"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Knight": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Monk": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Priest": {
        "races": [
          "human",
          "elf"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Rogue": {
        "races": [
          "human",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "Ranger": {
        "races": [
          "human",
          "elf",
          "gnome",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Samurai": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Tourist": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Valkyrie": {
        "races": [
          "human",
          "dwarf"
        ],
        "genders": [
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Wizard": {
        "races": [
          "human",
          "elf",
          "gnome",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      }
    },
    "raceConstraints": {
      "human": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "elf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "dwarf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "gnome": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "orc": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      }
    }
  },
  "3.7": {
    "roles": [
      "Archeologist",
      "Barbarian",
      "Caveman",
      "Healer",
      "Knight",
      "Monk",
      "Priest",
      "Rogue",
      "Ranger",
      "Samurai",
      "Tourist",
      "Valkyrie",
      "Wizard"
    ],
    "races": [
      "human",
      "elf",
      "dwarf",
      "gnome",
      "orc"
    ],
    "roleConstraints": {
      "Archeologist": {
        "races": [
          "human",
          "dwarf",
          "gnome"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Barbarian": {
        "races": [
          "human",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Caveman": {
        "races": [
          "human",
          "dwarf",
          "gnome"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Healer": {
        "races": [
          "human",
          "gnome"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Knight": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Monk": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Priest": {
        "races": [
          "human",
          "elf"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Rogue": {
        "races": [
          "human",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "Ranger": {
        "races": [
          "human",
          "elf",
          "gnome",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Samurai": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Tourist": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Valkyrie": {
        "races": [
          "human",
          "dwarf"
        ],
        "genders": [
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Wizard": {
        "races": [
          "human",
          "elf",
          "gnome",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      }
    },
    "raceConstraints": {
      "human": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "elf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "dwarf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "gnome": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "orc": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      }
    }
  },
  "slashem": {
    "roles": [
      "Archeologist",
      "Barbarian",
      "Caveman",
      "Flame Mage",
      "Healer",
      "Ice Mage",
      "Knight",
      "Monk",
      "Necromancer",
      "Priest",
      "Rogue",
      "Ranger",
      "Samurai",
      "Tourist",
      "Undead Slayer",
      "Valkyrie",
      "Wizard",
      "Yeoman"
    ],
    "races": [
      "doppelganger",
      "drow",
      "dwarf",
      "elf",
      "gnome",
      "hobbit",
      "human",
      "lycanthrope",
      "orc",
      "vampire"
    ],
    "roleConstraints": {
      "Archeologist": {
        "races": [
          "doppelganger",
          "dwarf",
          "elf",
          "gnome",
          "hobbit",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Barbarian": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "human",
          "lycanthrope",
          "orc",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Caveman": {
        "races": [
          "doppelganger",
          "dwarf",
          "gnome",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Flame Mage": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "gnome",
          "hobbit",
          "human",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Healer": {
        "races": [
          "doppelganger",
          "elf",
          "gnome",
          "hobbit",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Ice Mage": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "gnome",
          "hobbit",
          "human",
          "orc",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Knight": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Monk": {
        "races": [
          "doppelganger",
          "hobbit",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Necromancer": {
        "races": [
          "doppelganger",
          "drow",
          "human",
          "orc",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "Priest": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "hobbit",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Rogue": {
        "races": [
          "doppelganger",
          "human",
          "lycanthrope",
          "orc",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "Ranger": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "gnome",
          "hobbit",
          "human",
          "lycanthrope",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Samurai": {
        "races": [
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Tourist": {
        "races": [
          "doppelganger",
          "hobbit",
          "human"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Undead Slayer": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "gnome",
          "hobbit",
          "human",
          "lycanthrope",
          "orc"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Valkyrie": {
        "races": [
          "doppelganger",
          "dwarf",
          "human"
        ],
        "genders": [
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Wizard": {
        "races": [
          "doppelganger",
          "drow",
          "elf",
          "gnome",
          "hobbit",
          "human",
          "orc",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Yeoman": {
        "races": [
          "elf",
          "hobbit",
          "human"
        ],
        "genders": [
          "male"
        ],
        "aligns": [
          "lawful"
        ]
      }
    },
    "raceConstraints": {
      "doppelganger": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "drow": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "dwarf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "elf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "gnome": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "hobbit": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "human": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "lycanthrope": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "orc": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "vampire": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      }
    }
  },
  "evilhack": {
    "roles": [
      "Archeologist",
      "Barbarian",
      "Caveman",
      "Convict",
      "Druid",
      "Healer",
      "Infidel",
      "Knight",
      "Monk",
      "Priest",
      "Rogue",
      "Ranger",
      "Samurai",
      "Tourist",
      "Valkyrie",
      "Wizard",
      "Dark Knight"
    ],
    "races": [
      "human",
      "elf",
      "dwarf",
      "gnome",
      "orc",
      "giant",
      "hobbit",
      "centaur",
      "illithid",
      "tortle",
      "drow",
      "draugr",
      "vampire",
      "aasimar"
    ],
    "roleConstraints": {
      "Archeologist": {
        "races": [
          "human",
          "dwarf",
          "gnome",
          "hobbit",
          "tortle",
          "aasimar"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Barbarian": {
        "races": [
          "human",
          "dwarf",
          "orc",
          "giant",
          "centaur",
          "tortle",
          "draugr",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Caveman": {
        "races": [
          "human",
          "dwarf",
          "gnome",
          "giant",
          "aasimar"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Convict": {
        "races": [
          "human",
          "gnome",
          "orc",
          "illithid",
          "drow",
          "draugr",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "Druid": {
        "races": [
          "human",
          "elf",
          "giant",
          "hobbit",
          "centaur",
          "tortle"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Healer": {
        "races": [
          "human",
          "elf",
          "dwarf",
          "gnome",
          "giant",
          "hobbit",
          "centaur",
          "tortle"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Infidel": {
        "races": [
          "human",
          "elf",
          "orc",
          "giant",
          "centaur",
          "illithid",
          "drow",
          "draugr",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "Knight": {
        "races": [
          "human",
          "elf",
          "dwarf",
          "orc",
          "centaur",
          "drow",
          "draugr",
          "vampire",
          "aasimar"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "chaotic"
        ]
      },
      "Monk": {
        "races": [
          "human",
          "elf",
          "dwarf",
          "giant",
          "centaur",
          "tortle",
          "drow",
          "draugr",
          "vampire",
          "aasimar"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Priest": {
        "races": [
          "human",
          "elf",
          "dwarf",
          "orc",
          "giant",
          "hobbit",
          "centaur",
          "illithid",
          "tortle",
          "drow",
          "aasimar"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "Rogue": {
        "races": [
          "human",
          "elf",
          "gnome",
          "orc",
          "hobbit",
          "drow",
          "draugr",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Ranger": {
        "races": [
          "human",
          "elf",
          "gnome",
          "orc",
          "hobbit",
          "centaur",
          "drow"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Samurai": {
        "races": [
          "human",
          "dwarf",
          "giant",
          "tortle",
          "aasimar"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      },
      "Tourist": {
        "races": [
          "human",
          "gnome",
          "hobbit",
          "tortle"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral"
        ]
      },
      "Valkyrie": {
        "races": [
          "human",
          "dwarf",
          "giant",
          "centaur",
          "aasimar"
        ],
        "genders": [
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "Wizard": {
        "races": [
          "human",
          "elf",
          "dwarf",
          "gnome",
          "orc",
          "giant",
          "hobbit",
          "illithid",
          "tortle",
          "drow",
          "vampire"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "Dark Knight": {
        "races": [
          "human",
          "elf",
          "dwarf",
          "orc",
          "centaur",
          "drow",
          "draugr",
          "vampire",
          "aasimar"
        ],
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "chaotic"
        ]
      }
    },
    "raceConstraints": {
      "human": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "elf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "dwarf": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "gnome": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "orc": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "giant": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral",
          "chaotic"
        ]
      },
      "hobbit": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "centaur": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "neutral",
          "chaotic"
        ]
      },
      "illithid": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "tortle": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful",
          "neutral"
        ]
      },
      "drow": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "draugr": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "vampire": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "chaotic"
        ]
      },
      "aasimar": {
        "genders": [
          "male",
          "female"
        ],
        "aligns": [
          "lawful"
        ]
      }
    }
  }
} as const;
