/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Mon Apr 20 15:53:10 2026"
#define BUILD_TIME (1776693190UL)

#define VERSION_NUMBER 0x00090200UL
#define VERSION_FEATURES 0x00060040UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x40233232UL
#define VERSION_SANITY2 0x16113cbf0UL
#define VERSION_SANITY3 0x0002a000UL

#define VERSION_STRING "0.9.2"
#define VERSION_ID \
 "Unix EvilHack Version 0.9.2 - last build Mon Apr 20 15:53:10 2026."
#define COPYRIGHT_BANNER_C \
 "          Version 0.9.2 Unix, built Apr 20 15:53:10 2026."

#define NETHACK_GIT_SHA "13e4384e783520744302433a8ea6990e120c2ed6"
#define NETHACK_GIT_BRANCH "evilhack_wasm_spoofing"
